# Generated by Django 4.2.1 on 2023-05-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_miked', models.BooleanField(default=False)),
                ('is_direct', models.BooleanField(default=False)),
                ('num_channels', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_condenser', models.BooleanField(default=False)),
                ('is_dynamic', models.BooleanField(default=True)),
                ('takes_phantom_power', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_riders', to='lineup.act')),
                ('instruments', models.ManyToManyField(related_name='tech_riders', to='lineup.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('roles', models.ManyToManyField(related_name='people', to='lineup.role')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField()),
                ('acts', models.ManyToManyField(related_name='performances', to='lineup.act')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineup.show')),
                ('tech_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance', to='lineup.techrider')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='default_microphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.microphone'),
        ),
        migrations.AddField(
            model_name='act',
            name='performers',
            field=models.ManyToManyField(limit_choices_to={'roles__name': 'Performer'}, related_name='acts', to='lineup.person'),
        ),
        migrations.AddField(
            model_name='act',
            name='primary_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineup.person'),
        ),
    ]
