# Generated by Django 4.2.1 on 2023-05-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techrider',
            name='name',
        ),
    ]
