# Generated by Django 4.2.1 on 2023-05-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0002_remove_techrider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActTechRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_performers', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_riders', to='lineup.act')),
                ('instruments', models.ManyToManyField(related_name='tech_riders', to='lineup.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='TechSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('tech_riders', models.ManyToManyField(related_name='tech_specs', to='lineup.acttechrider')),
            ],
        ),
        migrations.RemoveField(
            model_name='performance',
            name='tech_rider',
        ),
        migrations.DeleteModel(
            name='TechRider',
        ),
        migrations.AddField(
            model_name='performance',
            name='tech_spec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance', to='lineup.techspec'),
        ),
    ]
