# Generated by Django 4.2.1 on 2023-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0003_acttechrider_techspec_remove_performance_tech_rider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techspec',
            name='tech_riders',
        ),
        migrations.AddField(
            model_name='acttechrider',
            name='setup_name',
            field=models.SlugField(default='None', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='techspec',
            name='acts',
            field=models.ManyToManyField(related_name='tech_specs', to='lineup.act'),
        ),
    ]
