# Generated by Django 4.2.1 on 2023-05-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0007_remove_acttechrider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='slug',
            field=models.SlugField(),
        ),
    ]
