# Generated by Django 4.2.1 on 2023-05-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0009_alter_performance_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='tech_spec',
        ),
        migrations.DeleteModel(
            name='TechSpec',
        ),
    ]
